name: React Native Android CI

on:
  push:
    branches:
      - master  # or "main" depending on your branch name
  pull_request:
    branches:
      - master

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant Execute Permission for Gradlew
        run: |
          cd android
          chmod +x gradlew

      - name: Build Android App
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SampleApp-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
